### ISSUE TITLE
Relation direction

### ISSUE THREAD

**Issue by serpilkuzu** [bounswe/bounswe2016group9#125]
Find the way to add direction to graph relations.
Retrieve directions data from back-end and prepare data to show in graph.

**Comment by isilkurt** [comment]
If we add another attribute to relations that can contain one content from 'to', 'from' or 'to, from', 
we can show relations more easily on frondend.

**Comment by mdogan93** [comment]
JSON object returns topics as I mentioned below.
  "fromTopic": {
...}
  "toTopic": {
...}
