### ISSUE TITLE
Meeting Today 

### ISSUE THREAD

**Issue by mdogan93** [bounswe/bounswe2016group9#3]
As we discussed at the meeting in last week, we will have a meeting today at 7:30 pm. We are asked to watch some videos and comment about them. Today, we will watch these videos together and we will make these comments written. 
P.S: Place will be decided via Telegram 
@alikirec @omerfaruktayfur @isilkurt @menafkasap @sehayigitguryol @mustafahaluk

**Comment by sehayigitguryol** [comment]
I've looked up a little bit on videos and I found they're interesting. We should look them together
