### ISSUE TITLE
Project Link

### ISSUE THREAD

**Issue by alpk** [bounswe/bounswe2016group9#37]
On your homepage the link is directed towards your tomcat homepage. I cannot login since I dont know your password. Please provide a link to your actual project page rather than your tomcat homepage:

example:
http://ec2-54-82-189-218.compute-1.amazonaws.com:8080/ourprojectname
instead of
http://ec2-54-82-189-218.compute-1.amazonaws.com:8080/

**Comment by menafkasap** [comment]
It is [http://ec2-54-82-189-218.compute-1.amazonaws.com:8080/InfoGrappo](http://ec2-54-82-189-218.compute-1.amazonaws.com:8080/InfoGrappo)
We forgot to change the link in the homepage. Thanks for the warning. We fixed it.
