### ISSUE TITLE
Requirement Check

### ISSUE THREAD

**Issue by sehayigitguryol** [bounswe/bounswe2016group9#56]
Don't forget to check corresponding requirements when doing your mockup jobs!

**Comment by menafkasap** [comment]
Is it done? 
Glossary is not completed yet and I think we have small mistakes in requirements

**Comment by menafkasap** [comment]
I think it is done now
[https://github.com/bounswe/bounswe2016group9/wiki/Requirements](https://github.com/bounswe/bounswe2016group9/wiki/Requirements)

**Comment by mdogan93** [comment]
Reviewing and revising will go on but we do not have full check again since our fundamentals are clearly defined in these requirements

**Comment by serpilkuzu** [comment]
Glossary part is completed.
