### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by sehayigitguryol** [bounswe/bounswe2016group9#58]
Update project plan according to schedule (@Piazza) and member roles.

**Comment by menafkasap** [comment]
Now you can update project plan via milestones
[https://github.com/bounswe/bounswe2016group9/milestones](https://github.com/bounswe/bounswe2016group9/milestones)

**Comment by menafkasap** [comment]
Can you update project plan according to costumer's desires? @omerfaruktayfur

**Comment by menafkasap** [comment]
Project plan added. Done
https://github.com/bounswe/bounswe2016group9/wiki/Project-Plan
