### ISSUE TITLE
Review Test Cases

### ISSUE THREAD

**Issue by menafkasap** [bounswe/bounswe2016group9#68]
Please review the testcases according to updated requirements #56  @isilkurt and @mustafahaluk

**Comment by mdogan93** [comment]
I ' ll complete up to end of 10th november

**Comment by menafkasap** [comment]
[https://docs.google.com/spreadsheets/d/1zsBnY4iT36C3dEl5MYiO8uuBc6FL4FauJISctPOSgUM/edit#gid=0](https://docs.google.com/spreadsheets/d/1zsBnY4iT36C3dEl5MYiO8uuBc6FL4FauJISctPOSgUM/edit#gid=0)

**Comment by isilkurt** [comment]
I completed my review.

**Comment by menafkasap** [comment]
Can you review again according to costumer's desires? @isilkurt @mustafahaluk
