### ISSUE TITLE
Create First Presentation Wiki Page

### ISSUE THREAD

**Issue by menafkasap** [bounswe/bounswe2016group9#69]
Please create a wiki page about the first presentation @serpilkuzu and @menafkasap

**Comment by menafkasap** [comment]
It is done
[https://github.com/bounswe/bounswe2016group9/wiki/First-Presentation](https://github.com/bounswe/bounswe2016group9/wiki/First-Presentation)

**Comment by serpilkuzu** [comment]
@menafkasap  and I completed the report.
