### ISSUE TITLE
Cross-origin request sharing(CORS) 

### ISSUE THREAD

**Issue by omutas** [bounswe/bounswe2016group9#75]
I cannot access to JSON object. We don't have access permission. Cross-origin request share should be implemented.

**Comment by mdogan93** [comment]
The problem is solved, could you confirm @omutas

**Comment by mdogan93** [comment]
Resolved!

**Comment by omutas** [comment]
It is working properly now

**Comment by mdogan93** [comment]
Closed!

**Comment by merteven** [comment]
This is just disabled for now. Will be reactivated later.

**Comment by merteven** [comment]
will be disabled permanently
